version: '3.8'

services:
  web:
    build: ./flaskr
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./flaskr/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev